version: '3'
services:
    myapp:
        build:
            context: .
        environment:
            DISCORD_TOKEN: ${DISCORD_TOKEN}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_NAME: ${DB_NAME}
